CREATE TABLE IF NOT EXISTS users
(
    user_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                                 NOT NULL,
    email VARCHAR(512)                                 NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items
(
    item_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(512)                            NOT NULL,
    available   bool                                    NOT NULL,
    owner_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_item PRIMARY KEY (item_id),
    FOREIGN KEY (owner_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings
(
    booking_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    finish      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    item_id     BIGINT                                  NOT NULL,
    booker_id   BIGINT                                  NOT NULL,
    status      VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY (booking_id),
    FOREIGN KEY (item_id) REFERENCES items (item_id) ON DELETE CASCADE,
    FOREIGN KEY (booker_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments
(
    comment_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    comment_text  VARCHAR(1000)                           NOT NULL,
    item_id       BIGINT                                  NOT NULL,
    author_id     BIGINT                                  NOT NULL,
    created_date  TIMESTAMP WITHOUT TIME ZONE             DEFAULT NOW(),
    CONSTRAINT pk_comment PRIMARY KEY (comment_id),
    FOREIGN KEY (item_id) REFERENCES items (item_id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS requests
(
    request_id   BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL,
    description  VARCHAR(2000)                             NOT NULL,
    requestor_id BIGINT                                    NOT NULL,
    created_date        TIMESTAMP WITHOUT TIME ZONE        DEFAULT NOW(),
    CONSTRAINT pk_request PRIMARY KEY (request_id),
    FOREIGN KEY (requestor_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS items_requests
(
    item_id     BIGINT   NOT NULL,
    request_id  BIGINT   NOT NULL,
    FOREIGN KEY (item_id) REFERENCES items (item_id) ON DELETE CASCADE,
    FOREIGN KEY (request_id) REFERENCES requests (request_id) ON DELETE CASCADE
);